; This is the full path to the "magick" executable program,
; including the executable itself.
pathToMagick = c:\imagemagick\magick.exe

; If you do NOT want to warn users about potential incompatibility
; issues with their terminal, set this to false.
; This will allow IcyTerm users to be able to view sixel images without 
; warning just fine, however, users of other terminals (e.g. Netrunner) 
; will see garbage dumped to the screen without a warning, or a reason why.
; In most cases it's best to leave this set to true.
unsupported_sixel_terminal_warning = true

; "resize" indicates whether to resize a sixel image to fill the height
; and width of the terminal when directly converting an image on the command line.
resize = true

; These are the allowed file formats including the dot (.), separated by semicolons (;).
imgFormats = .JPG;.JPEG;.GIF;.PNG;.BMP;.PCX;.TIF;.TIFF;.WEBP
txtFormats = .TXT;.ASC;.DOC;.NOW;.NWS;.NEW;.1ST
artFormats = .ANS;.MSG;.DIZ;.NFO;.ICE;.LIT;.TM;.SCR;.ART;.VT;.ART;.AD;.ACT;.MAG;.CIA;.LGO;.CAB;.001;.002;.003;.004;.1;.2;.3;.4;.5;.WKD;.TRI;.ALI;.NOE;.MIS;.MUS;.AMS;.BAD;.MEM;.SIT;.REL;.XB;.XBIN
filesWithoutExtensions = true

; Archive types:
;
; Each configured type must start with [archive_type] where "type"
; is the file extension of the archive minus the dot.
; "cmd" is the full path to the extraction utility for the archive type.
; ~file~ is the name of the archive.
; ~path~ is the temporary extraction path.
;
; Although you can specify any archive utility you want for each archive 
; type, 7-Zip (7z) is probably the best tool to use for all of them.
; Grab the latest version from: https://7-zip.org/
; After you install it, you should be able to run it by simply 
; typing "7z" on the command line. Then this command line format
; should work for nearly all archive types that you list below:
;   7z x -y ~file~ -o~path~

; This default will be used for any archive type where the cmd is left blank.
defaultArchiveExtractCmd = 7z x -y ~file~ -o~path~

[archive_zip]
cmd = %@unzip -o -qq ~file~ -d ~path~

[archive_rar]
cmd = 

[archive_7z]
cmd = 

[archive_arj]
cmd = 

